### PR TITLE
fix TypeError: this._layers is undefined

### PR DESCRIPTION
**Pull request by gegeweb**
### Fix
`TypeError: this._layers is undefined` when binding external layer(s).

### CODE REVIEW

**Comment by Raruto** [comment]
Hi Gèrald,
could you also kindly provide the offending code snippet?

**Comment by gegeweb** [comment]
At the same place than #58 ;)

```js
.on('routeselected', function(e) {
    elevationControl.clear(); // <- causes the error TypeError: this._layers is undefined
    elevationControl.addData(L.polyline(e.route.coordinates).toGeoJSON(), controlRouting.getLine());
    // controlRouting.getLine() return a L.FeatureGroup()
    if (elevationControl._container.style.display === "none") elevationControl.show();
    map.addControl(controlDownload);
    map.addControl(controlFit);
    let btn = L.DomUtil.get('download_route');
    L.DomUtil.removeClass(btn, 'hide');
})
.on('waypointschanged', function(e) {
    if (!plan.isReady()) {
        let btn = L.DomUtil.get('download_route');
        L.DomUtil.addClass(btn, 'hide');
        map.removeControl(controlDownload);
        map.removeControl(controlFit);
        elevationControl.clear();
        elevationControl.hide();
    }
})
.on('stepover', function(e) {
    controlRouting.getLine().fire('mousemove', { latlng: e.coord });
})
.on('stepout', function(e) {
    controlRouting.getLine().fire('mouseout', { latlng: e.coord })
});
```

The complete code is here:
https://framagit.org/gegeweb/scasb-calcul-itineraires-velo/-/blob/master/htdocs/assets/js/index.js

And patch in production: https://parcours.scasb.org

**Comment by Raruto** [comment]
In my last commit I changed it as a [L.FeatureGroup](https://leafletjs.com/reference-1.6.0.html#featuregroup) object.

Take a look it here:

https://github.com/Raruto/leaflet-elevation/blob/137ea6633bc9a4a8b63cfa0100910f7d4d92c9f6/src/control.js#L60

---

**PS** referring to the other pull, does it work if you change this line:

```js
elevationControl.addData(L.polyline(e.route.coordinates).toGeoJSON(), controlRouting.getLine());
```

to this other one?

```js
elevationControl.addData(L.GeoJSON.asFeature(e.route.coordinates), controlRouting.getLine());
```

**Comment by gegeweb** [comment]
> In my last commit I changed it as a [L.FeatureGroup](https://leafletjs.com/reference-1.6.0.html#featuregroup) object.

Yes, I've see that.
But in my case, the problem is there is no layers added by the plugin.

When the new route is calculated and selected (at the `routeselected` event), so the first time too, i add the data with addData and bind to the `L.FeatureGroup` already on the map.
And before updating data, I need to clear the previous.
I've modified Leaflet Routing Machine to use a `L.FeatureGroup` instead of a `L.LayerGroup` because `mousemove`and `mouseout`aren't fired with a LayerGroup.

So in my case, at init or when clearing before updating the data with `addData()` there is no layers added by the plugon and I bind to the existing.   

With the last commit I've another error:
`TypeError: layer.getElement is not a function` at control.js:517:22

in `_initLayer()`
```js
toggleClass(layer.getElement(), this.options.polyline.className + ' ' + this.options.theme);
```

I don't want to modify the layers in this context, just adding data and binding to the existing layer.

```js
elevationControl.addData(L.GeoJSON.asFeature(e.route.coordinates), controlRouting.getLine());
```
That works, but i always got the error above.

I think we can close this PR, and find another solution.
I'll try to use a `LayerGroup()` instead off `FeatureGroup()`, I think it should work.
But I dont want to modifie the class of polyline(s) in the group.

PS. I think the `dist/*` files should be ingnored and not synchronised by git. 

​

**Comment by gegeweb** [comment]
Using a `LayerGroup()` instead of `FeatureGroup()`change nothing.
That's because I bind an existing layer (I think), so `_initLayer`should be skipped.

In this app, i just need too display elevation and bind to the exiting layer for the tooltip and following marker.

The object (existing layer) get by `getLine():
https://github.com/perliedman/leaflet-routing-machine/blob/master/src/line.js

I've just modified to use a `FeatureGroup()`.

**Comment by gegeweb** [comment]
I'm closing this PR, not applicable since the last commit on master.
And I'm going to open an issue for my particular case: binding to an already existing layer on the map.

**Pull request closed without merging**
