### PR TITLE
Replace native `structuredClone` with custom `cloneDeep` function

### PR DESCRIPTION
**Pull request by Raruto**
Fixes a regression introduced by: https://github.com/Raruto/leaflet-elevation/pull/240

Closes: https://github.com/Raruto/leaflet-elevation/issues/255

### CODE REVIEW

**Comment by Raruto** [comment]
@hupe13 let me know.

**Comment by hupe13** [comment]
The error is gone, but I don't see both on my test page and on [your example](https://leafext.info/leaflet-elevation/examples/leaflet-elevation_string-data.html) the marker grafik.

**Comment by Raruto** [comment]
Check this out now and also check out the other examples with this change because it's quite likely that something else could be broken..

**Comment by hupe13** [comment]
I went through my test pages and didn't find any errors because of this, but I  found some errors in my application.
Your example works, but there is a warning that leaflet-rotate is missing.
What should I look for that might be broken?

**Comment by hupe13** [comment]
> > I went through my test pages and didn't find any errors because of this, but I found some errors in my application.

> I don't think I understand what you mean..

I found some errors in my code. (My english is not good, I'm using translators.)

**Comment by Raruto** [comment]
Ok, so I merge this pull request and then I release a new version so you can easily test all the latest changes together.

Ref: #252, #253, #254, #256 and #228

**Pull request merged**
