### PR TITLE
waypoints in gpx, get the track name

### PR DESCRIPTION
**Pull request by hupe13**
Hi Raruto,

if a gpx track contains waypoints (wpt), the name of tooltip was the name of the first waypoint. This pull request makes the name of the (first) track to the name of the tooltip.

This code removes the waypoints from map:

```js
map.on("zoomend", function(e) {
     map.eachLayer(function(layer) {
	if (layer instanceof L.Marker) {
	    map.removeLayer(layer);
	}
    });
});
```
I could not solve it any other way.

### CODE REVIEW

**Comment by Raruto** [comment]
@hupe13 https://leafletjs.com/reference#geojson-filter

> 
> This code removes the waypoints from map:
> 
> ```js
> map.on("zoomend", function(e) {
>      map.eachLayer(function(layer) {
> 	if (layer instanceof L.Marker) {
> 	    map.removeLayer(layer);
> 	}
>     });
> });
> ```
> 
> I could not solve it any other way.

@hupe13 take a look at https://leafletjs.com/reference#geojson-filter

**Comment by hupe13** [comment]
How do I filter L.GpxGroup?

**Comment by Raruto** [comment]
https://github.com/Raruto/leaflet-elevation/blob/fd739db55b147b864b79c41428757373551f59b7/libs/leaflet-gpxgroup.js#L232

Otherwise you can add a dedicated option if you want.

**Comment by hupe13** [comment]
Thank you very much, it works.

**Pull request merged**
