### PR TITLE
Fix #208 (min speed = 0)

### LINKED ISSUE #208: track.speed_min is always 0
Hi Raruto,

I have found that the minimum speed is always 0. The cause seems to be here:
https://github.com/Raruto/leaflet-elevation/blob/3ee745d71ed172979b7bfe0ff52f7c63214d3c04/src/handlers/speed.js#L18-L22

See your [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_speed-chart.html).

I tried different things, but I can't solve the problem. Can you help me please?

Thank you very much.

### PR DESCRIPTION
**Pull request by Raruto**
Close: https://github.com/Raruto/leaflet-elevation/issues/208 Close: https://github.com/Raruto/leaflet-elevation/issues/224 Close: https://github.com/Raruto/leaflet-elevation/issues/227

---

Related to:

- https://github.com/Raruto/leaflet-elevation/issues/208
- https://github.com/Raruto/leaflet-elevation/pull/216

TODO: check `skipNullZCoords` behavior (before / after this edit)

### CODE REVIEW

**Comment by Raruto** [comment]
Hi @hupe13,

If you have absolutely nothing to do, let me know what you think of these latest changes.

Surely they also introduce some related bugs due to the presence of `NaN` in the geojson layer (eg. when you try to display the hotline layer for a gpx file that is missing some altitude values).

BTW I guess this problem was introduced by the [_registerDataAttribute](https://github.com/Raruto/leaflet-elevation/commit/70e230fedf3d4786262e8db18c12c055d45f6997) during the 2.x refactoring (in trying to handle all the new extensions added in the `src/handlers` folder).

But anyway this is all my speculation (it's all code that I look at very occasionally..)

_Thanks for your patience,
Raruto_

**Comment by hupe13** [comment]
min speed seems to be okay.

**Comment by Raruto** [comment]
@hupe13 Related to: https://github.com/Raruto/leaflet-elevation/issues/224#issuecomment-1356356320, let me know if here we can proceed with the merge (or if other adjustments are needed) and subsequent release of the new version.

**Comment by hupe13** [comment]
I think so. I have tested it and it seems to be correct.

**Pull request merged**
