### PR TITLE
Add speed and acceleration graph

### PR DESCRIPTION
**Pull request by velocat**

### CODE REVIEW

**Comment by Raruto** [comment]
Hi velocat,

I updated your code a bit to make it work (eg. when the slope graph is disabled).
Let me know if anything is missing.

_Have a nice day,
Raruto_

**Comment by velocat** [comment]
It looks great :)

Although I consider Range to be redundant, since the speed cannot be negative. But maybe you are right, someone may need speed in a certain interval. ))

I would also add average speed in motion, in addition to average speed, since it is often that it is important. To do this, you need to set the initial value, from which it is considered that there was a movement)))

To this you can additionally get the time of movement / stops.

This is how I see it:
https://github.com/velocat/leaflet-elevation/commits/Movie-Speed%26-Time/src

**Comment by Raruto** [comment]
> I would also add average speed in motion, in addition to average speed, since it is often that it is important. To do this, you need to set the initial value, from which it is considered that there was a movement)))

I'm not sure this can be the most reliable strategy (what could happen in such a situation? https://stackoverflow.com/questions/9994128/strategies-to-detect-and-delete-cluttering-aggregations-of-gps-points)

**Comment by velocat** [comment]
> I'm not sure this can be the most reliable strategy

I read in one place that they tried to build an algorithm using logic:
This filtering algorithm is based on taking into account linear accelerations and angular velocities. Simply put, no vehicle has an acceleration greater than 1G at 0 km/h. The higher the speed, the lower the possible acceleration.

The same principle applies for angular speeds - nothing can turn 90 degrees in 1 second at 100 km/h.

**Comment by Raruto** [comment]
> there is an error with time formatting
> https://github.com/velocat/leaflet-elevation/commits/Movie-Speed%26-Time/src

This happens due to the [Date.toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) function.

But what you need would be more like the [Intl.DurationFormat](https://github.com/tc39/proposal-intl-duration-format) object (unfortunately only the [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) is implemented)

> I read in one place that they tried to build an algorithm using logic:
> This filtering algorithm is based on taking into account linear accelerations and angular velocities. 

Perhaps i think it would be better to directly rely on a specific third-party (server-side?) library to calculate these advanced kind of statistics, after that you can easily build your [custom summary](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_custom-summary.html).

The [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx/blob/98772565059f832326bb4d7594b5c0bdfd0aa94d/gpx.js#L522) library allows you to set the `max_point_interval` parameter for "motion" detection (even if you don't fully understand why...)

**Pull request merged**
