### PR TITLE
fix 'TypeError: controlElevation is undefined'

### PR DESCRIPTION
**Pull request by fgebhart**
After following the steps of your Readme.md file

```js
  // Instantiate elevation control.
  var controlElevation = L.control.elevation(elevation_options).addTo(map);

  // Load track from url (allowed data types: "*.geojson", "*.gpx")
  controlElevation.load("https://raruto.github.io/examples/leaflet-elevation/via-emilia.gpx");
```

I encountered the following error:
```
TypeError: controlElevation is undefined
```

This change solved it for me. 

```js
  var controlElevation = L.control.elevation(elevation_options);
  controlElevation.addTo(map);
```

### CODE REVIEW

**Comment by Raruto** [comment]
Can you try to do add the following instead?

```js
addTo: function(map) {
  if (this.options.detached) {
    this._addToChartDiv(map);
  } else {
    L.Control.prototype.addTo.call(this, map);
  }
  return this; // <-- add this line
},
```

source: [leaflet-elevation.js#L162](https://github.com/Raruto/leaflet-elevation/blob/323bd8659aa1554eb3590bb865ba2e9e2ae4a564/leaflet-elevation.js#L162)

**Comment by fgebhart** [comment]
ok, this also works for me 👍

**Comment by Raruto** [comment]
Ok, have you also tested with `detached` true / false?

**Comment by fgebhart** [comment]
Yes, both work totally fine.

**Comment by Raruto** [comment]
Ok, thanks for your help!

Patch released in **version [0.8.1](https://www.npmjs.com/package/@raruto/leaflet-elevation/v/0.8.1)**

**Pull request merged**
