### PR TITLE
Fix bug when layer have no _path

### PR DESCRIPTION
**Pull request by gegeweb**
Add L.polyline data (array of L.latLng) as gpx data to the chart.

### CODE REVIEW

**Comment by Raruto** [comment]
Hi Gérald,

could you kindly:

1. use the tab character as indentation? (so we can easily distinguish your changes...)
2. provide a more detailed description or example of your changes?

_Thanks for your cooperation,
Raruto_

**Comment by gegeweb** [comment]
You can check the code where i use this:
https://framagit.org/gegeweb/scasb-calcul-itineraires-velo/-/blob/master/htdocs/assets/js/index.js#L343

```
            .on('routeselected', function(e) {
                let coordinates = e.route.coordinates;
                elevationControl.clear();
                elevationControl.show();
                elevationControl.addData({ '_latlngs': coordinates }, controlRouting.getLine());
```
coordinates is an array of `L.latLng object`: `{lat: lat, lon: lon, alt: z}`and the layers returned by the function a `L.FeatureGroup object`.

**Comment by Raruto** [comment]
[Here](https://jsfiddle.net/nz7mhw8b/) you can see a simple example on how to effectively use an L.polyline as elevation object.

In your particular case, it could also be solved in this way:

```js
let _latlngs = e.route.coordinates; // same as polyline.getLatLngs()
let coords = L.GeoJSON.latLngsToCoords(e.route.coordinates);

elevationControl.addData({type: "Feature", geometry: { coordinates: coords, type: "LineString" }}, controlRouting.getLine());
```

Your solution is also quite correct, but I think it would be better to adopt a slightly cleaner / general one.

**Comment by gegeweb** [comment]
Yes you're right, this solution works fine, thanks !
So there is no need to modify addGPXData.

But we always need to check if layer have _path propertie in _clearPath or where adding class.

I'll update the PR by removing what's useless.

**Comment by gegeweb** [comment]
shorter, single line:
```
elevationControl.addData(L.polyline(e.route.coordinates).toGeoJSON(), controlRouting.getLine());
```

Thanks again, it looks better. ;)

**Pull request merged**
